defmodule Edict.Audit do
  @moduledoc """
  The static LiveView event audit behind `mix edict.audit`.

  Scans source files for `def handle_event/3` clauses and diffs their
  string-literal event names against the module's `authorize` declarations:

    * an event handled but never declared is **undeclared** — including every
      event of a view that forgot `use Edict.Enforcement.Authorize` entirely
    * a non-literal event name (`handle_event(name, ...)`) is
      **unverifiable** — reported, never a failure

  The scan is pure so tests and CI can run it directly; the Mix task is a
  thin wrapper. It is source-level, with known limits: events generated by
  macros are invisible, and `use MyAppWeb, :live_view` wrappers are only
  recognized by the `_live.ex` naming convention. Modules using
  `Phoenix.LiveComponent` are skipped — `authorize` does not support them.
  """

  defstruct [:path, :module, uses_authorize?: false, undeclared: [], unverifiable: []]

  @type t :: %__MODULE__{
          path: Path.t(),
          module: String.t() | nil,
          uses_authorize?: boolean(),
          undeclared: [String.t()],
          unverifiable: [String.t()]
        }

  @default_glob "lib/**/*.ex"

  @doc """
  Scans `source` (from `path`, named so in parse errors) and returns one
  finding per top-level module. Nested modules contribute to the enclosing
  finding.
  """
  @spec scan_source(String.t(), Path.t()) :: [t()]
  def scan_source(source, path) when is_binary(source) and is_binary(path) do
    source
    |> Code.string_to_quoted!(file: path)
    |> top_level_modules()
    |> Enum.flat_map(&scan_module(&1, path))
  end

  @doc """
  Reads and scans `paths`, returning only the findings worth reporting:
  modules with undeclared events or unverifiable dynamic event names.
  """
  @spec scan_paths([Path.t()]) :: [t()]
  def scan_paths(paths) do
    paths
    |> Enum.flat_map(&scan_source(File.read!(&1), &1))
    |> Enum.filter(&reportable?/1)
  end

  @doc """
  Expands `glob` (default `#{@default_glob}`) to the LiveView source files
  in scope: files using `Phoenix.LiveView` or `Edict.Enforcement.Authorize`,
  or named `*_live.ex`.
  """
  @spec find_sources(String.t()) :: [Path.t()]
  def find_sources(glob \\ @default_glob) do
    glob
    |> Path.wildcard()
    |> Enum.filter(&live_view_file?/1)
  end

  @doc """
  The audit's exit status: non-zero exactly when any finding has undeclared
  events. Unverifiable names never fail the audit.
  """
  @spec exit_status([t()]) :: :ok | {:shutdown, 1}
  def exit_status(findings) do
    if Enum.any?(findings, &(&1.undeclared != [])), do: {:shutdown, 1}, else: :ok
  end

  defp top_level_modules({:__block__, _, nodes}), do: Enum.filter(nodes, &defmodule?/1)

  defp top_level_modules(node), do: if(defmodule?(node), do: [node], else: [])

  defp defmodule?({:defmodule, _, [_, _]}), do: true
  defp defmodule?(_), do: false

  defp scan_module({:defmodule, _, [name, [do: body]]}, path) do
    acc =
      collect(body, %{
        uses_authorize?: false,
        live_component?: false,
        events: [],
        dynamic: [],
        declared: []
      })

    # A component cannot declare authorize guards, so its events are none of
    # the audit's business.
    if acc.live_component? do
      []
    else
      [finding(name, acc, path)]
    end
  end

  # Collects event names and declarations, stopping at function bodies: event
  # names live in handle_event clause heads (also under `when` guards), while
  # `use` and `authorize` sit at module level — a local `authorize/2` helper
  # called inside a body must not look like a declaration. Macro bodies are
  # pruned too: macro-generated events are a documented limit.
  defp collect({:def, _, [{:handle_event, _, [event | _]}, _]}, acc),
    do: collect_event(event, acc)

  defp collect({:def, _, [{:when, _, [{:handle_event, _, [event | _]}, _]}, _]}, acc),
    do: collect_event(event, acc)

  defp collect({kind, _, _}, acc) when kind in [:def, :defp, :defmacro, :defmacrop], do: acc

  defp collect({:use, _, [module | _]}, acc), do: collect_use(module, acc)

  defp collect({:authorize, _, [names | _]}, acc), do: collect_declared(names, acc)

  defp collect({_, _, args}, acc) when is_list(args), do: collect(args, acc)

  defp collect(nodes, acc) when is_list(nodes), do: Enum.reduce(nodes, acc, &collect/2)

  defp collect({left, right}, acc), do: collect(right, collect(left, acc))

  defp collect(_node, acc), do: acc

  defp collect_use({:__aliases__, _, [:Edict, :Enforcement, :Authorize]}, acc),
    do: %{acc | uses_authorize?: true}

  defp collect_use(:"Elixir.Edict.Enforcement.Authorize", acc),
    do: %{acc | uses_authorize?: true}

  defp collect_use({:__aliases__, _, [:Phoenix, :LiveComponent]}, acc),
    do: %{acc | live_component?: true}

  defp collect_use(:"Elixir.Phoenix.LiveComponent", acc), do: %{acc | live_component?: true}

  defp collect_use(_module, acc), do: acc

  defp collect_declared(names, acc) when is_binary(names),
    do: %{acc | declared: [names | acc.declared]}

  # The list form: every string element declares one event.
  defp collect_declared(names, acc) when is_list(names),
    do: %{acc | declared: acc.declared ++ Enum.filter(names, &is_binary/1)}

  # Anything else cannot compile — the authorize macro rejects non-literal
  # names — so there is nothing to record.
  defp collect_declared(_names, acc), do: acc

  defp collect_event(event, acc) when is_binary(event),
    do: %{acc | events: [event | acc.events]}

  # A variable, an underscore or an interpolation: the name is decided at
  # runtime, so the module's coverage cannot be verified.
  defp collect_event(event, acc), do: %{acc | dynamic: [Macro.to_string(event) | acc.dynamic]}

  defp finding(name, acc, path) do
    %__MODULE__{
      path: path,
      module: module_name(name),
      uses_authorize?: acc.uses_authorize?,
      undeclared:
        acc.events |> Enum.reverse() |> Enum.uniq() |> Kernel.--(Enum.uniq(acc.declared)),
      unverifiable: acc.dynamic |> Enum.reverse() |> Enum.uniq()
    }
  end

  defp module_name({:__aliases__, _, _} = name), do: Macro.to_string(name)
  defp module_name(name) when is_atom(name), do: inspect(name)
  defp module_name(_), do: nil

  defp reportable?(finding), do: finding.undeclared != [] or finding.unverifiable != []

  defp live_view_file?(path) do
    source = File.read!(path)

    String.contains?(source, "use Phoenix.LiveView") or
      String.contains?(source, "use Edict.Enforcement.Authorize") or
      String.ends_with?(path, "_live.ex")
  end
end
