defmodule Mix.Tasks.Edict.Audit do
  @moduledoc """
  Audits LiveView `handle_event/3` clauses against `authorize` declarations.

      mix edict.audit [path]

  `path` is a glob, `lib/**/*.ex` by default. Files using `Phoenix.LiveView`
  or `Edict.Enforcement.Authorize` — or named `*_live.ex` — are scanned;
  modules using `Phoenix.LiveComponent` are skipped.

  Each finding lists the module's undeclared events and unverifiable dynamic
  event names. The audit exits non-zero exactly when an undeclared event
  exists, which makes it a CI gate; unverifiable names are never failures.
  """

  @shortdoc "Audits LiveView events for missing authorize declarations"

  use Mix.Task

  @impl true
  def run(args) do
    glob = List.first(args) || "lib/**/*.ex"

    findings = glob |> Edict.Audit.find_sources() |> Edict.Audit.scan_paths()
    print(findings)

    if Edict.Audit.failed?(findings) do
      exit({:shutdown, 1})
    else
      :ok
    end
  end

  defp print([]) do
    Mix.shell().info("Edict audit: no undeclared LiveView events")
  end

  defp print(findings) do
    shell = Mix.shell()

    shell.info("Edict audit: #{length(findings)} module(s) with findings")

    Enum.each(findings, fn finding ->
      shell.info("")
      shell.info("#{finding.path} (#{finding.module || "unknown module"}):")
      print_finding(shell, finding)
    end)

    shell.error("")

    shell.error(
      "Known limits: events generated by macros are invisible to this scan; " <>
        "dynamic event names are unverifiable, not failures"
    )

    if Edict.Audit.failed?(findings) do
      shell.error("mix edict.audit found undeclared events")
    end
  end

  defp print_finding(shell, finding) do
    if finding.undeclared != [] do
      label =
        if finding.uses_authorize? do
          "undeclared events"
        else
          "undeclared events (the module never uses Edict.Enforcement.Authorize)"
        end

      shell.info("  #{label}: #{inspect(finding.undeclared)}")
    end

    if finding.unverifiable != [] do
      shell.info("  unverifiable dynamic event names: #{inspect(finding.unverifiable)}")
    end
  end
end
